In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

   RowNumber  CustomerId   Surname  CreditScore  ... HasCrCard IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave          619  ...         1              1        101348.88       1
1          2    15647311      Hill          608  ...         0              1        112542.58       0
2          3    15619304      Onio          502  ...         1              0        113931.57       1
3          4    15701354      Boni          699  ...         0              0         93826.63       0
4          5    15737888  Mitchell          850  ...         1              1         79084.10       0

[5 rows x 14 columns]

In [6]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis = 1)

In [7]:
data.head()

   CreditScore Geography  Gender  Age  Tenure  ...  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female   42       2  ...              1          1               1        101348.88       1
1          608     Spain  Female   41       1  ...              1          0               1        112542.58       0
2          502    France  Female   42       8  ...              3          1               0        113931.57       1
3          699    France  Female   39       1  ...              2          0               0         93826.63       0
4          850     Spain  Female   43       2  ...              1          1               1         79084.10       0

[5 rows x 11 columns]

In [8]:
label_encoder_gender = LabelEncoder()

In [9]:
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [10]:
data.head()

   CreditScore Geography  Gender  Age  Tenure  ...  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
0          619    France       0   42       2  ...              1          1               1        101348.88       1
1          608     Spain       0   41       1  ...              1          0               1        112542.58       0
2          502    France       0   42       8  ...              3          1               0        113931.57       1
3          699    France       0   39       1  ...              2          0               0         93826.63       0
4          850     Spain       0   43       2  ...              1          1               1         79084.10       0

[5 rows x 11 columns]

In [11]:
data.tail()

      CreditScore Geography  Gender  Age  Tenure  ...  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
9995          771    France       1   39       5  ...              2          1               0         96270.64       0
9996          516    France       1   35      10  ...              1          1               1        101699.77       0
9997          709    France       0   36       7  ...              1          0               1         42085.58       1
9998          772   Germany       1   42       3  ...              2          1               0         92888.52       1
9999          792    France       0   28       4  ...              1          1               0         38190.78       0

[5 rows x 11 columns]

In [12]:
onehot_encoder_geo = OneHotEncoder()

In [14]:
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()

In [15]:
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [20]:
columns = onehot_encoder_geo.get_feature_names_out(['Geography'])

In [52]:
columns

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [21]:
geo_encoded_df = pd.DataFrame(geo_encoder,columns=columns)

In [23]:
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [27]:
data = pd.concat([data.drop('Geography',axis = 1),geo_encoded_df],axis = 1)

In [28]:
data.head()

   CreditScore  Gender  Age  Tenure  ...  Exited  Geography_France  Geography_Germany  Geography_Spain
0          619       0   42       2  ...       1               1.0                0.0              0.0
1          608       0   41       1  ...       0               0.0                0.0              1.0
2          502       0   42       8  ...       1               1.0                0.0              0.0
3          699       0   39       1  ...       0               1.0                0.0              0.0
4          850       0   43       2  ...       0               0.0                0.0              1.0

[5 rows x 13 columns]

In [31]:
with open("label_encoder_gender.pkl","wb") as file:
    pickle.dump(label_encoder_gender,file)

with open("onehot_encoder_geo.pkl","wb") as file:
    pickle.dump(onehot_encoder_geo,file)

In [32]:
from sklearn.model_selection import train_test_split

In [53]:
x = data.drop('Exited',axis=1)

In [54]:
x.head()

   CreditScore  Gender  Age  Tenure  ...  EstimatedSalary  Geography_France  Geography_Germany  Geography_Spain
0          619       0   42       2  ...        101348.88               1.0                0.0              0.0
1          608       0   41       1  ...        112542.58               0.0                0.0              1.0
2          502       0   42       8  ...        113931.57               1.0                0.0              0.0
3          699       0   39       1  ...         93826.63               1.0                0.0              0.0
4          850       0   43       2  ...         79084.10               0.0                0.0              1.0

[5 rows x 12 columns]

In [37]:
y = data['Exited']

In [38]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [39]:
y.tail()

9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, dtype: int64

In [41]:
x_train , x_test , y_train , y_test = train_test_split(x, y ,test_size=0.2 , random_state=42)

In [42]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((8000, 12), (2000, 12), (8000,), (2000,))

In [43]:
scaler = StandardScaler()

In [46]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [47]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [48]:
x_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [49]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler , file)

In [51]:
data.head()

   CreditScore  Gender  Age  Tenure  ...  Exited  Geography_France  Geography_Germany  Geography_Spain
0          619       0   42       2  ...       1               1.0                0.0              0.0
1          608       0   41       1  ...       0               0.0                0.0              1.0
2          502       0   42       8  ...       1               1.0                0.0              0.0
3          699       0   39       1  ...       0               1.0                0.0              0.0
4          850       0   43       2  ...       0               0.0                0.0              1.0

[5 rows x 13 columns]

### ANN Implementation

In [58]:
!pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.20.0-cp313-cp313-win_amd64.whl.metadata (4.6 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow)
  Using cached flatbuffers-25.9.23-py2.py3-none-any.whl.metadata (875 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\chand\appdata\roaming\python\python313\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\chand\anaconda3\lib\site-packages (from tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\chand\anaconda3\lib\site-packages (from tensorflow) (2.31.0)
Requirement already satisfied: setuptools in c:\users\chand\anaconda3\lib\site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\chand\appdata\roaming\python\python313\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\chand\anaconda3\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\chand\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Using cached grpcio-1.75.1-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting tensorboard~=2.20.0 (from tensorflow)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.10.0 (from tensorflow)
  Using cached keras-3.11.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\chand\anaconda3\lib\site-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py>=3.11.0 in c:\users\chand\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Using cached ml_dtypes-0.5.3-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\chand\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\chand\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\chand\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chand\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.4.26)
Requirement already satisfied: markdown>=2.6.8 in c:\users\chand\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.8)
Requirement already satisfied: pillow in c:\users\chand\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.1.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.20.0->tensorflow)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\chand\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\chand\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\chand\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Collecting namex (from keras>=3.10.0->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.10.0->tensorflow)
  Using cached optree-0.17.0-cp313-cp313-win_amd64.whl.metadata (34 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\chand\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\chand\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\chand\appdata\roaming\python\python313\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\chand\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.0)
Using cached tensorflow-2.20.0-cp313-cp313-win_amd64.whl (332.0 MB)
Using cached grpcio-1.75.1-cp313-cp313-win_amd64.whl (4.6 MB)
Using cached ml_dtypes-0.5.3-cp313-cp313-win_amd64.whl (208 kB)
Using cached tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
Using cached tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Using cached absl_py-2.3.1-py3-none-any.whl (135 kB)
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Using cached flatbuffers-25.9.23-py2.py3-none-any.whl (30 kB)
Using cached gast-0.6.0-py3-none-any.whl (21 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Using cached keras-3.11.3-py3-none-any.whl (1.4 MB)
Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Using cached termcolor-3.1.0-py3-none-any.whl (7.7 kB)
Using cached namex-0.1.0-py3-none-any.whl (5.9 kB)
Using cached optree-0.17.0-cp313-cp313-win_amd64.whl (316 kB)
Installing collected packages: namex, libclang, flatbuffers, termcolor, tensorboard-data-server, optree, opt_einsum, ml_dtypes, grpcio, google_pasta, gast, astunparse, absl-py, tensorboard, keras, tensorflow

   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   ------- --------------------------------  3/16 [termcolor]
   ------------ ---------------------------  5/16 [optree]
   --------------- ------------------------  6/16 [opt_einsum]
   -------------------- -------------------  8/16 [grpcio]
   -------------------- -------------------  8/16 [grpcio]
   -------------------- -------------------  8/16 [grpcio]
   ---------------------- -----------------  9/16 [google_pasta]
   --------------------------- ------------ 11/16 [astunparse]
   ------------------------------ --------- 12/16 [absl-py]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   -------------------------------- ------- 13/16 [tensorboard]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ----------------------------------- ---- 14/16 [keras]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]
   ------------------------------------- -- 15/16 [tensorflow]

In [60]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [62]:
(x_train.shape[1],)

(12,)

In [66]:
## for the ANN model

model = Sequential([
        Dense(64,activation='relu',input_shape = (x_train.shape[1],)),
        Dense(32,activation='relu'),
        Dense(1,activation = 'sigmoid')
])

In [68]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 64)                  │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [90]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [91]:
## compiling the model

model.compile(optimizer=opt , loss = "binary_crossentropy" , metrics = ['accuracy'])

In [92]:
## Set up the Tensorboard
import datetime

logs_dir = "logs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=logs_dir , histogram_freq=1)

In [97]:
earlystop_callback = EarlyStopping(monitor = 'val_loss', patience=10, restore_best_weights=True)

In [98]:
## Train the model

history = model.fit(x_train , y_train , validation_data = (x_test,y_test) , epochs = 100 , callbacks = [tensorflow_callback , earlystop_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8634 - loss: 0.3308 - val_accuracy: 0.8620 - val_loss: 0.3389
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8621 - loss: 0.3293 - val_accuracy: 0.8595 - val_loss: 0.3439
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8664 - loss: 0.3254 - val_accuracy: 0.8600 - val_loss: 0.3528
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8684 - loss: 0.3220 - val_accuracy: 0.8605 - val_loss: 0.3468
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8680 - loss: 0.3220 - val_accuracy: 0.8590 - val_loss: 0.3437
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8664 - loss: 0.3195 - val_accuracy: 0.8605 - val_loss: 0.3468
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8701 - loss: 0.3182 - val_accuracy: 0.8595 - val_loss: 0.3538
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8700 - loss: 0.3136 - val_accuracy: 0.8585 - val_loss: 0.3604
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8724 - loss: 0.3134 - val_accuracy: 0.8550 - val_loss: 0.3591
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8740 - loss: 0.3108 - val_accuracy: 0.8565 - val_loss: 0.3603
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8710 - loss: 0.3097 - val_accuracy: 0.8560 - val_loss: 0.3581

In [99]:
from tensorflow.keras.models import load_model

model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [100]:
%load_ext tensorboard
%tensorboard --logdir logs/fit